name: glass_goals
description: App for being intentional about your Goals

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: 
    path: /Users/matt/documents/speech_to_text/speech_to_text

  rxdart: ^0.27.7
  uuid: ^3.0.7
  hlc: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gsheets: ^0.4.2
  screen_brightness: ^0.2.2
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    # not checked into repository
    - assets/local/sheet_creds.json
