name: goals_core
description: Core Library that would be shared by any app for displaying goals
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hlc: ^1.0.3
  rxdart: ^0.27.7
  uuid: ^4.1.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  goals_types: 
    path:
      ../goals_types
  collection: ^1.17.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.16.0
