name: goals_glass 
description: App for being intentional about your Goals

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: 
    path: /Users/matt/documents/speech_to_text/speech_to_text

  rxdart: ^0.27.7
  uuid: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  screen_brightness: ^0.2.2
  async: ^2.9.0
  goals_core:
    path: "../goals_core"
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    # not checked into repository
    - assets/local/sheet_creds.json
