name: goals_types_01
description: version 1.0 of the persisted types for glass_goals
version: 1.0.0
repository: https://github.com/AlabasterAxe/glass_goals

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
